### ISSUE TITLE
斯坦福cs224学习笔记pdf版

### ISSUE THREAD

**Issue by baozi-lala** [LooperXX/LooperXX.github.io#1]
https://github.com/LooperXX/LooperXX.github.io/issues请问有这个网址的学习笔记pdf版吗，能否分享一下，万分感谢

**Comment by yhshu** [comment]
我觉得您可以在该仓库下载 markdown 源码并通过 typora 等软件生成 pdf.

**Comment by baozi-lala** [comment]
好的，谢谢你

**Comment by baozi-lala** [comment]
你好，仓库里只有html文件，没有找到markdown源码

**Comment by yhshu** [comment]
这边建议您查阅下这个网页：
https://github.com/LooperXX/LooperXX.github.io/tree/master/docs

**Comment by baozi-lala** [comment]
![image](https://user-images.githubusercontent.com/21255466/64019476-d954f280-cb61-11e9-948f-6e6c3bd7d3d5.png)
在原本的Typora和生成的pdf中都有一些字符乱码的问题，请问这是什么原因导致的。
麻烦了。

**Comment by yhshu** [comment]
您确定是在 typora 中使用 pandoc 生成的 pdf 吗？
https://support.typora.io/Install-and-Use-Pandoc/

**Comment by baozi-lala** [comment]
是的，一开始我在typora中有这个问题，后来我下载了pandoc，还是有这个问题

**Comment by yhshu** [comment]
请确认使用 typora 时关闭了源代码模式，或重启 typora 尝试。

**Comment by baozi-lala** [comment]
我在偏好设置里重新设置了typora 的编辑器，问题已经解决，万分感谢

**Comment by LooperXX** [comment]
已在 https://github.com/LooperXX/CS224n-2019-Reading-Notes 发布 pdf
